const users = [
    {
        userID: 1,
        isAdmin: true,
        userName: "KisaLisa",
        userPass: "Pipipupu69",
        userEmail: "kisaLisa@gmail.com"
    },
    {
        userID: 2,
        isAdmin: true,
        userName: "Gerralt",
        userPass: "G-T",
        userEmail: "gt@gmail.com"
    },
    {
        userID: 3,
        isAdmin: false,
        userName: "RT14",
        userPass: "RT14",
        userEmail: "rt14@gmail.com"
    },
    {
        userID: 4,
        isAdmin: false,
        userName: "RT10",
        userPass: "RT10",
        userEmail: "rt10@gmail.com"
    },
    {
        userID: 5,
        isAdmin: false,
        userName: "RT6",
        userPass: "RT6",
        userEmail: "rt6@gmail.com"
    },
    {
        userID: 6,
        isAdmin: false,
        userName: "RT2",
        userPass: "RT2",
        userEmail: "rt2@gmail.com"
    }
];

const cards  = [
    {
        cardID: 1,
        cardName: "Alakazam",
        cardImg: "https://den-cards.pokellector.com/119/Alakazam.BS.1.png",
        actionStartingDate: new Date("2024-09-05"),
        auctionEndDate: new Date("2024-09-15"),
        auctionStartingBid: 150.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Psychic",
        cardRate: 7.5,
        bids: []
    },
    {
        cardID: 2,
        cardName: "Blastoise",
        cardImg: "https://den-cards.pokellector.com/119/Blastoise.BS.2.png",
        actionStartingDate: new Date("2024-09-10"),
        auctionEndDate: new Date("2024-09-20"),
        auctionStartingBid: 5000.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Water",
        cardRate: 8.5,
        bids: []
    },
    {
        cardID: 3,
        cardName: "Chansey",
        cardImg: "https://den-cards.pokellector.com/119/Chansey.BS.3.png",
        actionStartingDate: new Date("2024-09-12"),
        auctionEndDate: new Date("2024-09-22"),
        auctionStartingBid: 120.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Normal",
        cardRate: 7.5,
        bids: []
    },
    {
        cardID: 4,
        cardName: "Charizard",
        cardImg: "https://den-cards.pokellector.com/119/Charizard.BS.4.png",
        actionStartingDate: new Date("2024-09-08"),
        auctionEndDate: new Date("2024-09-18"),
        auctionStartingBid: 10000.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 7.0,
        bids: []
    },
    {
        cardID: 6,
        cardName: "Gyarados",
        cardImg: "https://den-cards.pokellector.com/119/Gyarados.BS.6.png",
        actionStartingDate: new Date("2024-09-15"),
        auctionEndDate: new Date("2024-09-25"),
        auctionStartingBid: 800.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Water",
        cardRate: 8.0,
        bids: []
    },
    {
        cardID: 8,
        cardName: "Machamp",
        cardImg: "https://den-cards.pokellector.com/119/Machamp.BS.8.png",
        actionStartingDate: new Date("2024-09-06"),
        auctionEndDate: new Date("2024-09-16"),
        auctionStartingBid: 3000.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fighting",
        cardRate: 8.0,
        bids: []
    },
    {
        cardID: 10,
        cardName: "Mewtwo",
        cardImg: "https://den-cards.pokellector.com/119/Mewtwo.BS.10.png",
        actionStartingDate: new Date("2024-09-11"),
        auctionEndDate: new Date("2024-09-21"),
        auctionStartingBid: 7500.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Psychic",
        cardRate: 9.0,
        bids: []
    },
    {
        cardID: 12,
        cardName: "Ninetales",
        cardImg: "https://den-cards.pokellector.com/119/Ninetales.BS.12.png",
        actionStartingDate: new Date("2024-09-07"),
        auctionEndDate: new Date("2024-09-17"),
        auctionStartingBid: 950.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 8.0,
        bids: []
    },
    {
        cardID: 14,
        cardName: "Raichu",
        cardImg: "https://den-cards.pokellector.com/119/Raichu.BS.14.png",
        actionStartingDate: new Date("2024-09-13"),
        auctionEndDate: new Date("2024-09-23"),
        auctionStartingBid: 300.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Electric",
        cardRate: 7.0,
        bids: []
    },
    {
        cardID: 15,
        cardName: "Venusaur",
        cardImg: "https://den-cards.pokellector.com/119/Venusaur.BS.15.png",
        actionStartingDate: new Date("2024-09-15"),
        auctionEndDate: new Date("2024-09-25"),
        auctionStartingBid: 8000.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Grass",
        cardRate: 9.5,
        bids: []
    },
    {
        cardID: 16,
        cardName: "Zapdos",
        cardImg: "https://den-cards.pokellector.com/119/Zapdos.BS.16.png",
        actionStartingDate: new Date("2024-09-08"),
        auctionEndDate: new Date("2024-09-18"),
        auctionStartingBid: 1200.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Electric",
        cardRate: 9.0,
        bids: []
    },
    {
        cardID: 18,
        cardName: "Dragonair",
        cardImg: "https://den-cards.pokellector.com/119/Dragonair.BS.18.png",
        actionStartingDate: new Date("2024-09-12"),
        auctionEndDate: new Date("2024-09-22"),
        auctionStartingBid: 800.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Normal",
        cardRate: 8.5,
        bids: []
    },
    {
        cardID: 20,
        cardName: "Electabuzz",
        cardImg: "https://den-cards.pokellector.com/119/Electabuzz.BS.20.png",
        actionStartingDate: new Date("2024-09-18"),
        auctionEndDate: new Date("2024-09-28"),
        auctionStartingBid: 600.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Electric",
        cardRate: 7.5,
        bids: []
    },
    {
        cardID: 23,
        cardName: "Arcanine",
        cardImg: "https://den-cards.pokellector.com/119/Arcanine.BS.23.png",
        actionStartingDate: new Date("2024-09-13"),
        auctionEndDate: new Date("2024-09-23"),
        auctionStartingBid: 350.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 8.5,
        bids: []
    },
    {
        cardID: 25,
        cardName: "Dewgong",
        cardImg: "https://den-cards.pokellector.com/119/Dewgong.BS.25.png",
        actionStartingDate: new Date("2024-09-06"),
        auctionEndDate: new Date("2024-09-16"),
        auctionStartingBid: 200.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Water",
        cardRate: 6.5,
        bids: []
    },
    {
        cardID: 26,
        cardName: "Dratini",
        cardImg: "https://den-cards.pokellector.com/119/Dratini.BS.26.png",
        actionStartingDate: new Date("2024-09-08"),
        auctionEndDate: new Date("2024-09-18"),
        auctionStartingBid: 150.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Normal",
        cardRate: 6.0,
        bids: []
    },
    {
        cardID: 28,
        cardName: "Growlithe",
        cardImg: "https://den-cards.pokellector.com/119/Growlithe.BS.28.png",
        actionStartingDate: new Date("2024-09-12"),
        auctionEndDate: new Date("2024-09-22"),
        auctionStartingBid: 600.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 7.5,
        bids: []
    },
    {
        cardID: 29,
        cardName: "Haunter",
        cardImg: "https://den-cards.pokellector.com/119/Haunter.BS.29.png",
        actionStartingDate: new Date("2024-09-14"),
        auctionEndDate: new Date("2024-09-24"),
        auctionStartingBid: 350.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Psychic",
        cardRate: 8.0,
        bids: []
    },
    {
        cardID: 35,
        cardName: "Magikarp",
        cardImg: "https://den-cards.pokellector.com/119/Magikarp.BS.35.png",
        actionStartingDate: new Date("2024-09-11"),
        auctionEndDate: new Date("2024-09-21"),
        auctionStartingBid: 50.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Water",
        cardRate: 6.5,
        bids: []
    },
    {
        cardID: 36,
        cardName: "Magmar",
        cardImg: "https://den-cards.pokellector.com/119/Magmar.BS.36.png",
        actionStartingDate: new Date("2024-09-13"),
        auctionEndDate: new Date("2024-09-23"),
        auctionStartingBid: 300.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 7.5,
        bids: []
    },
    {
        cardID: 46,
        cardName: "Charmander",
        cardImg: "https://den-cards.pokellector.com/119/Charmander.BS.46.png",
        actionStartingDate: new Date("2024-09-05"),
        auctionEndDate: new Date("2024-09-15"),
        auctionStartingBid: 500.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 9.0,
        bids: []
    },
    {
        cardID: 50,
        cardName: "Gastly",
        cardImg: "https://den-cards.pokellector.com/119/Gastly.BS.50.png",
        actionStartingDate: new Date("2024-09-14"),
        auctionEndDate: new Date("2024-09-24"),
        auctionStartingBid: 500.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Psychic",
        cardRate: 8.5,
        bids: []
    },
    {
        cardID: 58,
        cardName: "Pikachu",
        cardImg: "https://den-cards.pokellector.com/119/Pikachu.BS.58.png",
        actionStartingDate: new Date("2024-09-15"),
        auctionEndDate: new Date("2024-09-25"),
        auctionStartingBid: 1000.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Electric",
        cardRate: 9.5,
        bids: []
    },
    {
        cardID: 96,
        cardName: "Double Colorless Energy",
        cardImg: "https://den-cards.pokellector.com/119/Double-Colorless-Energy.BS.96.png",
        actionStartingDate: new Date("2024-09-25"),
        auctionEndDate: new Date("2024-10-05"),
        auctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Colorless",
        cardRate: 6.0,
        bids: []
    },
    {
        cardID: 97,
        cardName: "Fighting Energy",
        cardImg: "https://den-cards.pokellector.com/119/Fighting-Energy.BS.97.png",
        actionStartingDate: new Date("2024-09-27"),
        auctionEndDate: new Date("2024-10-07"),
        auctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Fighting",
        cardRate: 7.0,
        bids: []
    },
    {
        cardID: 98,
        cardName: "Fire Energy",
        cardImg: "https://den-cards.pokellector.com/119/Fire-Energy.BS.98.png",
        actionStartingDate: new Date("2024-09-29"),
        auctionEndDate: new Date("2024-10-09"),
        auctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Fire",
        cardRate: 7.5,
        bids: []
    },
    {
        cardID: 99,
        cardName: "Grass Energy",
        cardImg: "https://den-cards.pokellector.com/119/Grass-Energy.BS.99.png",
        actionStartingDate: new Date("2024-10-01"),
        auctionEndDate: new Date("2024-10-11"),
        auctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Grass",
        cardRate: 6.5,
        bids: []
    },
    {
        cardID: 100,
        cardName: "Lightning Energy",
        cardImg: "https://den-cards.pokellector.com/119/Lightning-Energy.BS.100.png",
        actionStartingDate: new Date("2024-10-03"),
        auctionEndDate: new Date("2024-10-13"),
        auctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Electric",
        cardRate: 7.0,
        bids: []
    },
    {
        cardID: 101,
        cardName: "Psychic Energy",
        cardImg: "https://den-cards.pokellector.com/119/Psychic-Energy.BS.101.png",
        actionStartingDate: new Date("2024-10-05"),
        auctionEndDate: new Date("2024-10-15"),
        auctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Psychic",
        cardRate: 6.0,
        bids: []
    },
    {
        cardID: 102,
        cardName: "Water Energy",
        cardImg: "https://den-cards.pokellector.com/119/Water-Energy.BS.102.png",
        actionStartingDate: new Date("2024-10-07"),
        auctionEndDate: new Date("2024-10-17"),
        auctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Water",
        cardRate: 7.5,
        bids: []
    }
];

export const data = {
    cards: [
        {
            cardID: 1,
            cardName: "Alakazam",
            cardImg: "https://den-cards.pokellector.com/119/Alakazam.BS.1.png",
            actionStartingDate: new Date("2024-10-05"),
            auctionEndDate: new Date("2024-10-15"),
            auctionStartingBid: 150.00,
            cardType: "Pokemon",
            energyType: "Psychic",
            cardRate: 7.5,
            bids: []
        },
        {
            cardID: 2,
            cardName: "Blastoise",
            cardImg: "https://den-cards.pokellector.com/119/Blastoise.BS.2.png",
            actionStartingDate: new Date("2024-10-10"),
            auctionEndDate: new Date("2024-11-20"),
            auctionStartingBid: 5000.00,
            cardType: "Pokemon",
            energyType: "Water",
            cardRate: 8.5,
            bids: []
        },
        {
            cardID: 3,
            cardName: "Chansey",
            cardImg: "https://den-cards.pokellector.com/119/Chansey.BS.3.png",
            actionStartingDate: new Date("2024-10-12"),
            auctionEndDate: new Date("2024-10-22"),
            auctionStartingBid: 120.00,
            cardType: "Pokemon",
            energyType: "Normal",
            cardRate: 7.5,
            bids: []
        },
        {
            cardID: 4,
            cardName: "Charizard",
            cardImg: "https://den-cards.pokellector.com/119/Charizard.BS.4.png",
            actionStartingDate: new Date("2024-10-08"),
            auctionEndDate: new Date("2024-10-18"),
            auctionStartingBid: 10000.00,
            cardType: "Pokemon",
            energyType: "Fire",
            cardRate: 7.0,
            bids: []
        },
        {
            cardID: 6,
            cardName: "Gyarados",
            cardImg: "https://den-cards.pokellector.com/119/Gyarados.BS.6.png",
            actionStartingDate: new Date("2024-10-15"),
            auctionEndDate: new Date("2024-10-25"),
            auctionStartingBid: 800.00,
            cardType: "Pokemon",
            energyType: "Water",
            cardRate: 8.0,
            bids: []
        },
        {
            cardID: 8,
            cardName: "Machamp",
            cardImg: "https://den-cards.pokellector.com/119/Machamp.BS.8.png",
            actionStartingDate: new Date("2024-10-06"),
            auctionEndDate: new Date("2024-10-16"),
            auctionStartingBid: 3000.00,
            cardType: "Pokemon",
            energyType: "Fighting",
            cardRate: 8.0,
            bids: []
        },
        {
            cardID: 10,
            cardName: "Mewtwo",
            cardImg: "https://den-cards.pokellector.com/119/Mewtwo.BS.10.png",
            actionStartingDate: new Date("2024-10-11"),
            auctionEndDate: new Date("2024-10-21"),
            auctionStartingBid: 7500.00,
            cardType: "Pokemon",
            energyType: "Psychic",
            cardRate: 9.0,
            bids: []
        },
        {
            cardID: 12,
            cardName: "Ninetales",
            cardImg: "https://den-cards.pokellector.com/119/Ninetales.BS.12.png",
            actionStartingDate: new Date("2024-10-07"),
            auctionEndDate: new Date("2024-10-17"),
            auctionStartingBid: 950.00,
            cardType: "Pokemon",
            energyType: "Fire",
            cardRate: 8.0,
            bids: []
        },
        {
            cardID: 14,
            cardName: "Raichu",
            cardImg: "https://den-cards.pokellector.com/119/Raichu.BS.14.png",
            actionStartingDate: new Date("2024-10-13"),
            auctionEndDate: new Date("2024-10-23"),
            auctionStartingBid: 300.00,
            cardType: "Pokemon",
            energyType: "Electric",
            cardRate: 7.0,
            bids: []
        },
        {
            cardID: 15,
            cardName: "Venusaur",
            cardImg: "https://den-cards.pokellector.com/119/Venusaur.BS.15.png",
            actionStartingDate: new Date("2024-10-15"),
            auctionEndDate: new Date("2024-10-25"),
            auctionStartingBid: 8000.00,
            cardType: "Pokemon",
            energyType: "Grass",
            cardRate: 9.5,
            bids: []
        },
        {
            cardID: 16,
            cardName: "Zapdos",
            cardImg: "https://den-cards.pokellector.com/119/Zapdos.BS.16.png",
            actionStartingDate: new Date("2024-10-08"),
            auctionEndDate: new Date("2024-10-18"),
            auctionStartingBid: 1200.00,
            cardType: "Pokemon",
            energyType: "Electric",
            cardRate: 9.0,
            bids: []
        },
        {
            cardID: 18,
            cardName: "Dragonair",
            cardImg: "https://den-cards.pokellector.com/119/Dragonair.BS.18.png",
            actionStartingDate: new Date("2024-10-12"),
            auctionEndDate: new Date("2024-10-22"),
            auctionStartingBid: 800.00,
            cardType: "Pokemon",
            energyType: "Normal",
            cardRate: 8.5,
            bids: []
        },
        {
            cardID: 20,
            cardName: "Electabuzz",
            cardImg: "https://den-cards.pokellector.com/119/Electabuzz.BS.20.png",
            actionStartingDate: new Date("2024-10-18"),
            auctionEndDate: new Date("2024-10-28"),
            auctionStartingBid: 600.00,
            cardType: "Pokemon",
            energyType: "Electric",
            cardRate: 7.5,
            bids: []
        },
        {
            cardID: 23,
            cardName: "Arcanine",
            cardImg: "https://den-cards.pokellector.com/119/Arcanine.BS.23.png",
            actionStartingDate: new Date("2024-10-13"),
            auctionEndDate: new Date("2024-10-23"),
            auctionStartingBid: 350.00,
            cardType: "Pokemon",
            energyType: "Fire",
            cardRate: 8.5,
            bids: []
        },
        {
            cardID: 25,
            cardName: "Dewgong",
            cardImg: "https://den-cards.pokellector.com/119/Dewgong.BS.25.png",
            actionStartingDate: new Date("2024-10-06"),
            auctionEndDate: new Date("2024-10-16"),
            auctionStartingBid: 200.00,
            cardType: "Pokemon",
            energyType: "Water",
            cardRate: 6.5,
            bids: []
        },
        {
            cardID: 26,
            cardName: "Dratini",
            cardImg: "https://den-cards.pokellector.com/119/Dratini.BS.26.png",
            actionStartingDate: new Date("2024-10-08"),
            auctionEndDate: new Date("2024-10-18"),
            auctionStartingBid: 150.00,
            cardType: "Pokemon",
            energyType: "Normal",
            cardRate: 6.0,
            bids: []
        },
        {
            cardID: 28,
            cardName: "Growlithe",
            cardImg: "https://den-cards.pokellector.com/119/Growlithe.BS.28.png",
            actionStartingDate: new Date("2024-10-12"),
            auctionEndDate: new Date("2024-10-22"),
            auctionStartingBid: 600.00,
            cardType: "Pokemon",
            energyType: "Fire",
            cardRate: 7.5,
            bids: []
        },
        {
            cardID: 29,
            cardName: "Haunter",
            cardImg: "https://den-cards.pokellector.com/119/Haunter.BS.29.png",
            actionStartingDate: new Date("2024-10-14"),
            auctionEndDate: new Date("2024-10-24"),
            auctionStartingBid: 350.00,
            cardType: "Pokemon",
            energyType: "Psychic",
            cardRate: 8.5,
            bids: []
        },
        {
            cardID: 35,
            cardName: "Magikarp",
            cardImg: "https://den-cards.pokellector.com/119/Magikarp.BS.35.png",
            actionStartingDate: new Date("2024-10-11"),
            auctionEndDate: new Date("2024-10-21"),
            auctionStartingBid: 50.00,
            cardType: "Pokemon",
            energyType: "Water",
            cardRate: 6.5,
            bids: []
        },
        {
            cardID: 36,
            cardName: "Magmar",
            cardImg: "https://den-cards.pokellector.com/119/Magmar.BS.36.png",
            actionStartingDate: new Date("2024-10-13"),
            auctionEndDate: new Date("2024-10-23"),
            auctionStartingBid: 300.00,
            cardType: "Pokemon",
            energyType: "Fire",
            cardRate: 7.5,
            bids: []
        },
        {
            cardID: 46,
            cardName: "Charmander",
            cardImg: "https://den-cards.pokellector.com/119/Charmander.BS.46.png",
            actionStartingDate: new Date("2024-10-05"),
            auctionEndDate: new Date("2024-10-15"),
            auctionStartingBid: 500.00,
            cardType: "Pokemon",
            energyType: "Fire",
            cardRate: 9.0,
            bids: []
        },
        {
            cardID: 50,
            cardName: "Gastly",
            cardImg: "https://den-cards.pokellector.com/119/Gastly.BS.50.png",
            actionStartingDate: new Date("2024-10-14"),
            auctionEndDate: new Date("2024-10-24"),
            auctionStartingBid: 500.00,
            cardType: "Pokemon",
            energyType: "Psychic",
            cardRate: 8.5,
            bids: []
        },
        {
            cardID: 58,
            cardName: "Pikachu",
            cardImg: "https://den-cards.pokellector.com/119/Pikachu.BS.58.png",
            actionStartingDate: new Date("2024-10-15"),
            auctionEndDate: new Date("2024-10-25"),
            auctionStartingBid: 1000.00,
            cardType: "Pokemon",
            energyType: "Electric",
            cardRate: 9.5,
            bids: []
        },
        {
            cardID: 96,
            cardName: "Normal Energy",
            cardImg: "https://den-cards.pokellector.com/119/Double-Colorless-Energy.BS.96.png",
            actionStartingDate: new Date("2024-10-25"),
            auctionEndDate: new Date("2024-11-05"),
            auctionStartingBid: 75.00,
            cardType: "Energy",
            energyType: "Normal",
            cardRate: 6.0,
            bids: []
        },
        {
            cardID: 97,
            cardName: "Fighting Energy",
            cardImg: "https://den-cards.pokellector.com/119/Fighting-Energy.BS.97.png",
            actionStartingDate: new Date("2024-10-27"),
            auctionEndDate: new Date("2024-11-07"),
            auctionStartingBid: 75.00,
            cardType: "Energy",
            energyType: "Fighting",
            cardRate: 7.0,
            bids: []
        },
        {
            cardID: 98,
            cardName: "Fire Energy",
            cardImg: "https://den-cards.pokellector.com/119/Fire-Energy.BS.98.png",
            actionStartingDate: new Date("2024-10-29"),
            auctionEndDate: new Date("2024-11-09"),
            auctionStartingBid: 75.00,
            cardType: "Energy",
            energyType: "Fire",
            cardRate: 7.5,
            bids: []
        },
        {
            cardID: 99,
            cardName: "Grass Energy",
            cardImg: "https://den-cards.pokellector.com/119/Grass-Energy.BS.99.png",
            actionStartingDate: new Date("2024-11-01"),
            auctionEndDate: new Date("2024-11-11"),
            auctionStartingBid: 75.00,
            cardType: "Energy",
            energyType: "Grass",
            cardRate: 6.5,
            bids: []
        },
        {
            cardID: 100,
            cardName: "Lightning Energy",
            cardImg: "https://den-cards.pokellector.com/119/Lightning-Energy.BS.100.png",
            actionStartingDate: new Date("2024-11-03"),
            auctionEndDate: new Date("2024-11-13"),
            auctionStartingBid: 75.00,
            cardType: "Energy",
            energyType: "Electric",
            cardRate: 7.0,
            bids: []
        },
        {
            cardID: 101,
            cardName: "Psychic Energy",
            cardImg: "https://den-cards.pokellector.com/119/Psychic-Energy.BS.101.png",
            actionStartingDate: new Date("2024-11-05"),
            auctionEndDate: new Date("2024-11-15"),
            auctionStartingBid: 75.00,
            cardType: "Energy",
            energyType: "Psychic",
            cardRate: 6.0,
            bids: []
        },
        {
            cardID: 102,
            cardName: "Water Energy",
            cardImg: "https://den-cards.pokellector.com/119/Water-Energy.BS.102.png",
            actionStartingDate: new Date("2024-11-07"),
            auctionEndDate: new Date("2024-11-17"),
            auctionStartingBid: 75.00,
            cardType: "Energy",
            energyType: "Water",
            cardRate: 7.5,
            bids: []
        }
    ],
    
    users: [
        {
            userID: 1,
            isAdmin: true,
            userPass: "$2a$10$UNubya/7SbOC3xkGW/LiYOvh1h9Ac7bc/MMgUxYDN4Z6JcszHIvAC", //Pipipupu69
            userEmail: "KisaAlisa@gmail.com"
        },
        {
            userID: 2,
            isAdmin: true,
            userPass: "$2a$10$8CsJGh9d43KYGV7FipXDTOQMpieMzwH6p.EjGHtpGUlu2DL0uD3qO", //Gt123
            userEmail: "gt@gmail.com"
        },
        {
            userID: 3,
            isAdmin: false,
            userPass: "$2a$10$NXfbjhhouscrAKwNDSbgf.K9FWyKLQWcba6RYu6DJnGDmiJjOyngm", // Rt14
            userEmail: "rt14@gmail.com"
        },
        {
            userID: 4,
            isAdmin: false,
            userPass: "$2a$10$msMlORDzIt22RW1TICP6aeMDI8No.NiuT1454s1vfFfyN5Fpmw0Yy", //Rt10
            userEmail: "rt10@gmail.com"
        },
        {
            userID: 5,
            isAdmin: false,
            userPass: "$2a$10$TpgB6oD14psKN/Gk421.Ru0vy1MZOQkjjF3WRfRgNYy9J4Icns4ku",  //Rt6
            userEmail: "rt6@gmail.com"
        },
        {
            userID: 6,
            isAdmin: false,
            userPass: "$2a$10$gtntej7QymxcqGAhkFALIemi9W7r/qKWL965gabT7fT7JGgKwtTm2", //Rt2
            userEmail: "rt2@gmail.com"
        }]
}