const users = [
    {
        userID: 1,
        isAdmin: true,
        userName: "KisaLisa",
        userPass: "Pipipupu69",
        userEmail: "kisaLisa@gmail.com"
    },
    {
        userID: 2,
        isAdmin: true,
        userName: "Gerralt",
        userPass: "G-T",
        userEmail: "gt@gmail.com"
    },
    {
        userID: 3,
        isAdmin: false,
        userName: "RT14",
        userPass: "RT14",
        userEmail: "rt14@gmail.com"
    },
    {
        userID: 4,
        isAdmin: false,
        userName: "RT10",
        userPass: "RT10",
        userEmail: "rt10@gmail.com"
    },
    {
        userID: 5,
        isAdmin: false,
        userName: "RT6",
        userPass: "RT6",
        userEmail: "rt6@gmail.com"
    },
    {
        userID: 6,
        isAdmin: false,
        userName: "RT2",
        userPass: "RT2",
        userEmail: "rt2@gmail.com"
    }
];

const cards  = [
    {
        cardID: 1,
        cardName: "Alakazam",
        cardImg: "https://den-cards.pokellector.com/119/Alakazam.BS.1.png",
        actionStartingDate: new Date("2024-09-05"),
        auctionEndDate: new Date("2024-09-15"),
        auctionStartingBid: 150.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Psychic",
        cardRate: 7.5,
        bids: []
    },
    {
        cardID: 2,
        cardName: "Blastoise",
        cardImg: "https://den-cards.pokellector.com/119/Blastoise.BS.2.png",
        actionStartingDate: new Date("2024-09-10"),
        auctionEndDate: new Date("2024-09-20"),
        auctionStartingBid: 5000.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Water",
        cardRate: 8.5,
        bids: []
    },
    {
        cardID: 3,
        cardName: "Chansey",
        cardImg: "https://den-cards.pokellector.com/119/Chansey.BS.3.png",
        actionStartingDate: new Date("2024-09-12"),
        auctionEndDate: new Date("2024-09-22"),
        auctionStartingBid: 120.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Normal",
        cardRate: 7.5,
        bids: []
    },
    {
        cardID: 4,
        cardName: "Charizard",
        cardImg: "https://den-cards.pokellector.com/119/Charizard.BS.4.png",
        actionStartingDate: new Date("2024-09-08"),
        auctionEndDate: new Date("2024-09-18"),
        auctionStartingBid: 10000.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 7.0,
        bids: []
    },
    {
        cardID: 6,
        cardName: "Gyarados",
        cardImg: "https://den-cards.pokellector.com/119/Gyarados.BS.6.png",
        actionStartingDate: new Date("2024-09-15"),
        auctionEndDate: new Date("2024-09-25"),
        auctionStartingBid: 800.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Water",
        cardRate: 8.0,
        bids: []
    },
    {
        cardID: 8,
        cardName: "Machamp",
        cardImg: "https://den-cards.pokellector.com/119/Machamp.BS.8.png",
        actionStartingDate: new Date("2024-09-06"),
        auctionEndDate: new Date("2024-09-16"),
        auctionStartingBid: 3000.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fighting",
        cardRate: 8.0,
        bids: []
    },
    {
        cardID: 10,
        cardName: "Mewtwo",
        cardImg: "https://den-cards.pokellector.com/119/Mewtwo.BS.10.png",
        actionStartingDate: new Date("2024-09-11"),
        auctionEndDate: new Date("2024-09-21"),
        auctionStartingBid: 7500.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Psychic",
        cardRate: 9.0,
        bids: []
    },
    {
        cardID: 12,
        cardName: "Ninetales",
        cardImg: "https://den-cards.pokellector.com/119/Ninetales.BS.12.png",
        actionStartingDate: new Date("2024-09-07"),
        auctionEndDate: new Date("2024-09-17"),
        auctionStartingBid: 950.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 8.0,
        bids: []
    },
    {
        cardID: 14,
        cardName: "Raichu",
        cardImg: "https://den-cards.pokellector.com/119/Raichu.BS.14.png",
        actionStartingDate: new Date("2024-09-13"),
        auctionEndDate: new Date("2024-09-23"),
        auctionStartingBid: 300.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Electric",
        cardRate: 7.0,
        bids: []
    },
    {
        cardID: 15,
        cardName: "Venusaur",
        cardImg: "https://den-cards.pokellector.com/119/Venusaur.BS.15.png",
        actionStartingDate: new Date("2024-09-15"),
        auctionEndDate: new Date("2024-09-25"),
        auctionStartingBid: 8000.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Grass",
        cardRate: 9.5,
        bids: []
    },
    {
        cardID: 16,
        cardName: "Zapdos",
        cardImg: "https://den-cards.pokellector.com/119/Zapdos.BS.16.png",
        actionStartingDate: new Date("2024-09-08"),
        auctionEndDate: new Date("2024-09-18"),
        auctionStartingBid: 1200.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Electric",
        cardRate: 9.0,
        bids: []
    },
    {
        cardID: 18,
        cardName: "Dragonair",
        cardImg: "https://den-cards.pokellector.com/119/Dragonair.BS.18.png",
        actionStartingDate: new Date("2024-09-12"),
        auctionEndDate: new Date("2024-09-22"),
        auctionStartingBid: 800.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Dragon",
        cardRate: 8.5,
        bids: []
    },
    {
        cardID: 20,
        cardName: "Electabuzz",
        cardImg: "https://den-cards.pokellector.com/119/Electabuzz.BS.20.png",
        actionStartingDate: new Date("2024-09-18"),
        auctionEndDate: new Date("2024-09-28"),
        auctionStartingBid: 600.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Electric",
        cardRate: 7.5,
        bids: []
    },
    {
        cardID: 23,
        cardName: "Arcanine",
        cardImg: "https://den-cards.pokellector.com/119/Arcanine.BS.23.png",
        actionStartingDate: new Date("2024-09-13"),
        auctionEndDate: new Date("2024-09-23"),
        auctionStartingBid: 350.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 8.5,
        bids: []
    },
    {
        cardID: 25,
        cardName: "Dewgong",
        cardImg: "https://den-cards.pokellector.com/119/Dewgong.BS.25.png",
        actionStartingDate: new Date("2024-09-06"),
        auctionEndDate: new Date("2024-09-16"),
        auctionStartingBid: 200.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Water",
        cardRate: 6.5,
        bids: []
    },
    {
        cardID: 26,
        cardName: "Dratini",
        cardImg: "https://den-cards.pokellector.com/119/Dratini.BS.26.png",
        actionStartingDate: new Date("2024-09-08"),
        auctionEndDate: new Date("2024-09-18"),
        auctionStartingBid: 150.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Dragon",
        cardRate: 6.0,
        bids: []
    },
    {
        cardID: 28,
        cardName: "Growlithe",
        cardImg: "https://den-cards.pokellector.com/119/Growlithe.BS.28.png",
        actionStartingDate: new Date("2024-09-12"),
        auctionEndDate: new Date("2024-09-22"),
        auctionStartingBid: 600.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 7.5,
        bids: []
    },
    {
        CardID: 29,
        CardName: "Haunter",
        CardImg: "https://den-cards.pokellector.com/119/Haunter.BS.29.png",
        ActionStartingDate: new Date("2024-09-14"),
        AuctionEndDate: new Date("2024-09-24"),
        AuctionStartingBid: 350.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Psychic",
        cardRate: 8.0,
        bids: []
    },
    {
        CardID: 35,
        CardName: "Magikarp",
        CardImg: "https://den-cards.pokellector.com/119/Magikarp.BS.35.png",
        ActionStartingDate: new Date("2024-09-11"),
        AuctionEndDate: new Date("2024-09-21"),
        AuctionStartingBid: 50.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Water",
        cardRate: 6.5,
        bids: []
    },
    {
        CardID: 36,
        CardName: "Magmar",
        CardImg: "https://den-cards.pokellector.com/119/Magmar.BS.36.png",
        ActionStartingDate: new Date("2024-09-13"),
        AuctionEndDate: new Date("2024-09-23"),
        AuctionStartingBid: 300.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 7.5,
        bids: []
    },
    {
        CardID: 46,
        CardName: "Charmander",
        CardImg: "https://den-cards.pokellector.com/119/Charmander.BS.46.png",
        ActionStartingDate: new Date("2024-09-05"),
        AuctionEndDate: new Date("2024-09-15"),
        AuctionStartingBid: 500.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Fire",
        cardRate: 9.0,
        bids: []
    },
    {
        CardID: 50,
        CardName: "Gastly",
        CardImg: "https://den-cards.pokellector.com/119/Gastly.BS.50.png",
        ActionStartingDate: new Date("2024-09-14"),
        AuctionEndDate: new Date("2024-09-24"),
        AuctionStartingBid: 500.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Psychic",
        cardRate: 8.5,
        bids: []
    },
    {
        CardID: 58,
        CardName: "Pikachu",
        CardImg: "https://den-cards.pokellector.com/119/Pikachu.BS.58.png",
        ActionStartingDate: new Date("2024-09-15"),
        AuctionEndDate: new Date("2024-09-25"),
        AuctionStartingBid: 1000.00,
        wasSold: false,
        cardType: "Pokemon",
        energyType: "Electric",
        cardRate: 9.5,
        bids: []
    },
    {
        CardID: 96,
        CardName: "Double Colorless Energy",
        CardImg: "https://den-cards.pokellector.com/119/Double-Colorless-Energy.BS.96.png",
        ActionStartingDate: new Date("2024-09-25"),
        AuctionEndDate: new Date("2024-10-05"),
        AuctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Colorless",
        cardRate: 6.0,
        bids: []
    },
    {
        CardID: 97,
        CardName: "Fighting Energy",
        CardImg: "https://den-cards.pokellector.com/119/Fighting-Energy.BS.97.png",
        ActionStartingDate: new Date("2024-09-27"),
        AuctionEndDate: new Date("2024-10-07"),
        AuctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Fighting",
        cardRate: 7.0,
        bids: []
    },
    {
        CardID: 98,
        CardName: "Fire Energy",
        CardImg: "https://den-cards.pokellector.com/119/Fire-Energy.BS.98.png",
        ActionStartingDate: new Date("2024-09-29"),
        AuctionEndDate: new Date("2024-10-09"),
        AuctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Fire",
        cardRate: 7.5,
        bids: []
    },
    {
        CardID: 99,
        CardName: "Grass Energy",
        CardImg: "https://den-cards.pokellector.com/119/Grass-Energy.BS.99.png",
        ActionStartingDate: new Date("2024-10-01"),
        AuctionEndDate: new Date("2024-10-11"),
        AuctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Grass",
        cardRate: 6.5,
        bids: []
    },
    {
        CardID: 100,
        CardName: "Lightning Energy",
        CardImg: "https://den-cards.pokellector.com/119/Lightning-Energy.BS.100.png",
        ActionStartingDate: new Date("2024-10-03"),
        AuctionEndDate: new Date("2024-10-13"),
        AuctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Electric",
        cardRate: 7.0,
        bids: []
    },
    {
        CardID: 101,
        CardName: "Psychic Energy",
        CardImg: "https://den-cards.pokellector.com/119/Psychic-Energy.BS.101.png",
        ActionStartingDate: new Date("2024-10-05"),
        AuctionEndDate: new Date("2024-10-15"),
        AuctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Psychic",
        cardRate: 6.0,
        bids: []
    },
    {
        CardID: 102,
        CardName: "Water Energy",
        CardImg: "https://den-cards.pokellector.com/119/Water-Energy.BS.102.png",
        ActionStartingDate: new Date("2024-10-07"),
        AuctionEndDate: new Date("2024-10-17"),
        AuctionStartingBid: 75.00,
        wasSold: false,
        cardType: "Energy",
        energyType: "Water",
        cardRate: 7.5,
        bids: []
    }
];